config/routes.rb
Blogarr::Application.routes.draw do
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  root :to => 'posts#index'

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :user_id
  validates :title, presence: true
  validates :content, presence: true
  
  scope :recent, order("created_at DESC").limit(5)
  
  belongs_to :user

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name

  validates_uniqueness_of :email
  
  has_many :posts, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, only: [:create, :edit, :update, :new, :destroy]
  
  def index
    @posts = Post.recent
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params[:post])
    @post.user_id = params[:user_id]
    if @post.save
      redirect_to @post, notice: 'A post has been created successfully'
    else
      render 'new'
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to posts_path, notice: 'Post has been updated'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [Redcarpet::Render::HTML, :hard_wrap => true, :safe_links_only => true, :autolink => true, :space_after_headers => true]
    md = Redcarpet::Markdown.new(*options)
    
    md.render(text).html_safe
      
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogarr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">

    <div class="header">
      <%= render 'shared/header' %>
    </div>
    
    <div class="content">
      <%= yield %>
    </div>
    
    <div class="sidebar">
      <%= render 'shared/sidebar' %>
    </div>
    
    <div class="footer">
      <%= render 'shared/footer' %>
    </div>
    
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <h1><%= f.label :title %></h1>
  <%= f.text_field :title %>
  
  <h1><%= f.label :content %></h1>
  <%= f.text_area :content %>
  
  <%= hidden_field_tag 'user_id', current_user.id %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% if current_user %>
	<h2><%= link_to 'New Post', new_post_path %></h2>
<% end %>

<% @posts.each do |post| %>
	<div class="post">  
		<h2><%= link_to post.title, post %></h2> 
		<h3><%= post.created_at.strftime("%b %e at %l:%M%p") %> by <%= User.find(post.user_id).first_name %></h3>
		<p><%= markdown(truncate(post.content, :length => 500)) %></p>
		<% if current_user %>
		  <div class="admin-controls">
		    <%= link_to 'Edit', edit_post_path(post) %> - 
  		    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }%></h4>
  		  </div>
  		<% end %>
  	</div>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<%= render 'form' %>
  

app/views/posts/show.html.erb
<h2><%= link_to @post.title, post_path(@post) %> </h2>
<h3><%= @post.created_at.strftime("%b %e at %l:%M%p") %> by <%= User.find(@post.user_id).first_name %> </h3>
<%= markdown(@post.content) %>

<% if current_user %>
	<div class="admin-controls">
	    <%= link_to 'Edit', edit_post_path(@post) %> - 
	    <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }%></h4>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<h1>This is a footer</h1>

app/views/shared/_header.html.erb
<h2><%= link_to "Blogarr", posts_path %></h2>

<div class="login-actions">
	<% if current_user %>
	  Logged in as <%= current_user.email %>.
	  <%= link_to "Log Out", logout_path %>
	<% else %>
	  <%= link_to "Sign Up", signup_path %> or
	  <%= link_to "Log In", login_path %>
	<% end %>
</div>

app/views/shared/_sidebar.html.erb
<h1>This is a sidebar</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>